# -*- coding: utf-8 -*-
"""MinstDataSet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/133aWBXkWBexDTrvCi22W71oDXuOJ-Ly2

In The Name Of God

Input LIbrary
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist

from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical

"""                     Get Data from Database"""

(X_train, y_train), (X_test, y_test)  = mnist.load_data()

"""👀👀👀👀👀👀"""

X_train

"""Dimension of Input"""

X_train.shape

"""Reshaping for CNN Input"""

X_train_plus = np.expand_dims(X_train, axis = -1 ) / 255

X_test_plus = np.expand_dims(X_test, axis = -1 ) / 255

X_train_plus.shape

"""ONE-HOT"""

Y_train_plus = to_categorical(y_train, 10)
Y_test_plus = to_categorical(y_test, 10)

Y_train_plus

"""Middle Layer"""

CNN = Sequential()

CNN.add(Conv2D(filters = 12, kernel_size = (3, 3), activation= 'relu', input_shape = (28, 28, 1)))
CNN.add(Conv2D(filters = 16, kernel_size = (3, 3), activation= 'relu'))
CNN.add(MaxPooling2D(pool_size=(2,2)))
CNN.add(Flatten())
CNN.add(Dense(16, activation = 'relu'))
CNN.add(Dense(10, activation = 'softmax'))

CNN.compile(loss= "categorical_crossentropy", optimizer = "adam" ,metrics = ["accuracy"])

"""SUmmary We dont have any freezed Item"""

CNN.summary()

"""Learn Model"""

cm = CNN.fit(X_train_plus,Y_train_plus, batch_size= 128, epochs = 20, validation_data=(X_test_plus,Y_test_plus),shuffle =True)

"""PLOT"""

plt.plot(cm.history['loss'])
plt.plot(cm.history['val_loss'])
plt.title('N(model lossN:)')
plt.xlabel("N(epoch)N")
plt.ylabel("N(loss)N")
plt.legend(["Train" ,"Validation"] ,loc = "upper right")
plt.show()

plt.plot(cm.history['accuracy'])
plt.plot(cm.history['val_accuracy'])
plt.title('N(Model accuracyN:)')
plt.ylabel('N(Accuracy)N')
plt.xlabel('N(Epoch)N')
plt.legend(['Train', 'Validation'], loc='lower right')
plt.show()

"""**Predict** AND MAX OF ROW"""

yp = np.argmax(CNN.predict(X_test_plus), axis=1)

from sklearn.metrics import confusion_matrix ,classification_report
cm = confusion_matrix(y_test, np.argmax(CNN.predict(X_test_plus), axis=1))

cm

"""export Data to excel"""

import pandas as pd
cmmm = pd.DataFrame(cm)
cmmm.to_csv('cm.csv')

print(classification_report(y_test, yp))

ddmm=print(classification_report(y_test, yp))



"""                     **GUTTEN** **ABEND**"""